#!/usr/bin/env bash
# Move the Next.js rebuild into the raulji-group repo.
#
# Non-destructive: the existing Vite app is moved to legacy-vite/ on a new
# branch, not deleted, so nothing is lost and the diff is reviewable.
set -euo pipefail

REPO="${1:-/Users/yuvrajsinhraulji/Documents/GitHub/raulji-group}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Repo:   $REPO"
echo "Source: $SRC"
echo

if [ ! -w "$REPO" ]; then
  echo "ERROR: $REPO is not writable by $(id -un)."
  echo "Run this first, then re-run this script:"
  echo "  sudo chown -R \$(id -un):staff \"$REPO\""
  exit 1
fi

cd "$REPO"
git config --global --add safe.directory "$REPO" 2>/dev/null || true

if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree is not clean. Commit or stash first."
  exit 1
fi

git checkout -b nextjs-phase-1

# Park the Vite app rather than deleting it.
mkdir -p legacy-vite
for f in src index.html vite.config.ts vitest.config.ts eslint.config.js \
         components.json bun.lock bun.lockb tsconfig.app.json tsconfig.node.json; do
  [ -e "$f" ] && git mv "$f" "legacy-vite/" 2>/dev/null || true
done

# Old static sitemap/robots are now generated by app/sitemap.ts and app/robots.ts.
for f in public/sitemap.xml public/robots.txt public/placeholder.svg; do
  [ -e "$f" ] && git rm -q "$f" || true
done

# Copy the new app in. supabase/ and .git/ are untouched.
rsync -a --exclude node_modules --exclude .next --exclude migrate-into-repo.sh \
      --exclude tsconfig.tsbuildinfo "$SRC/" "$REPO/"

cat > .gitignore <<'GITIGNORE'
node_modules/
.next/
out/
build/
.env
.env.local
.env*.local
.DS_Store
*.tsbuildinfo
.vercel
npm-debug.log*
GITIGNORE

echo
echo "Done. Next:"
echo "  cd \"$REPO\""
echo "  npm install"
echo "  cp .env.example .env.local   # then fill in RAULJI_CRM_API_KEY"
echo "  npm run dev"
echo
echo "Review with: git status && git diff --stat"
