// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[city]" | "/[city]/[service]" | "/about" | "/blog" | "/blog/[slug]" | "/compare" | "/contact" | "/disclaimer" | "/faqs" | "/gujarat" | "/privacy" | "/services" | "/services/[slug]" | "/services/business-consulting" | "/services/business-registration" | "/team" | "/terms"
type AppRouteHandlerRoutes = "/api/lead" | "/og" | "/rentals"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/business-consulting" | "/business-registration" | "/industries" | "/rent" | "/rent/[[...path]]" | "/services/company-registration" | "/services/consulting" | "/services/land-investment" | "/services/registration"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[city]": { "city": string; }
  "/[city]/[service]": { "city": string; "service": string; }
  "/about": {}
  "/api/lead": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/business-consulting": {}
  "/business-registration": {}
  "/compare": {}
  "/contact": {}
  "/disclaimer": {}
  "/faqs": {}
  "/gujarat": {}
  "/industries": {}
  "/og": {}
  "/privacy": {}
  "/rent": {}
  "/rent/[[...path]]": { "path"?: string[]; }
  "/rentals": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/services/business-consulting": {}
  "/services/business-registration": {}
  "/services/company-registration": {}
  "/services/consulting": {}
  "/services/land-investment": {}
  "/services/registration": {}
  "/team": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
