import type { StaticImageData } from "next/image";

import office from "@/public/photos/raulji-group-office.webp";
import consulting from "@/public/photos/raulji-group-business-consulting.webp";
import registration from "@/public/photos/raulji-group-company-registration.webp";
import meeting from "@/public/photos/raulji-group-client-meeting.webp";
import documents from "@/public/photos/raulji-group-documents.webp";
import gujarat from "@/public/photos/raulji-group-gujarat.webp";
import technologies from "@/public/photos/raulji-technologies.webp";
import enquiry from "@/public/photos/raulji-group-enquiry.webp";

/**
 * The image slots from the plan in AUDIT.md.
 *
 * These are drawn artwork: illustrated skylines for the place panels, brand
 * line work for the rest, the Raulji mark, and a line of type. Finished
 * pieces, not grey boxes waiting to be filled, so the pages read as designed
 * rather than unbuilt. Every pixel is generated by
 * `scratchpad/gen-scenes.py` and `gen-panels.py`, so they can be re-rendered
 * at any size.
 *
 * They are also not photographs, and nothing about them pretends otherwise.
 * Each one draws something the page is already saying (a building elevation
 * over "Vadodara, Gujarat", a decision splitting into structures over
 * "Business consulting"), and the alt text describes what is actually on
 * screen. That is the line the brand rules draw: no invented offices, no stock
 * people, nothing presented as Raulji Group that is not (master rule 1).
 *
 * Real photography still beats them and should replace them slot by slot. The
 * handover is a file swap, not a code change: drop the photograph into
 * `public/photos/` under the same filename and update the alt text to describe
 * the photograph.
 *
 * `placeholder` stays in the type for anything added later that is a genuine
 * stand-in. Flagged entries render a visible marker and never take `priority`.
 */
export interface BrandImageEntry {
  src: StaticImageData;
  alt: string;
  placeholder: boolean;
}

export const IMAGES = {
  office: {
    src: office,
    alt: "Illustrated city skyline, captioned Vadodara, Gujarat",
    placeholder: false,
  },
  consulting: {
    src: consulting,
    alt: "Business consulting at Raulji Group: clearer decisions",
    placeholder: false,
  },
  registration: {
    src: registration,
    alt: "Company registration handled by Raulji Group",
    placeholder: false,
  },
  meeting: {
    src: meeting,
    alt: "Talk to the Raulji Group team",
    placeholder: false,
  },
  documents: {
    src: documents,
    alt: "The documents a business registration needs",
    placeholder: false,
  },
  gujarat: {
    src: gujarat,
    alt: "Illustrated city skyline, captioned Business across Gujarat",
    placeholder: false,
  },
  technologies: {
    src: technologies,
    alt: "Raulji Technologies, the group's separate technology brand",
    placeholder: false,
  },
  enquiry: {
    src: enquiry,
    alt: "Tell Raulji Group what you are building",
    placeholder: false,
  },
} as const satisfies Record<string, BrandImageEntry>;

export type ImageSlot = keyof typeof IMAGES;
